server:
  port: 8083
spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  type-aliases-package: com.zhr.student.entity.*
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    auto-mapping-behavior: full
logging:
  level:
    com.zhr.student: debug
    org.springframework.web: debug
    org.springframework.transaction: debug
    org.mybatis: debug
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
