server:
  port: 8083
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/student
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4jtrue

mybatis:
  type-aliases-package: com.zhr.student.entity.*
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    auto-mapping-behavior: full
logging:
  level:
    com.zhr.student: debug
    org.springframework.web: debug
    org.springframework.transaction: debug
    org.mybatis: debug
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
